import { createSelection } from "../app/index.js";

export const state = {
  sources: {},
  locIndex: null,
  trace: null,
  traceText: "",
  traceNote: "",
  traceIndex: -1,
  diffRows: [],
  diffBefore: null,
  diffAfter: null,
  diffCursor: -1,
  traceDiffTitle: "",
  profile: { timing: null, memory: null, matches: [] },
  renderedText: "",
  traceCounts: null,
  traceBuffers: null,
  canvasView: "graph",
  gpuModel: null,
  localModel: null,
  localWanted: true,
  traceSymbols: null,
  opModel: null,
  opShapes: null,
  opPinned: null,
  benchmarks: { baseline: null, current: null },
  measured: null,
  timer: 0,
  debugOn: false,
  breakpoints: [],
  bpHits: new Map(),
  inspectorSaved: {},
  restored: false,
  explainedLine: -1,
  opMarkInfo: new Map(),
  lastOpEntries: null,
};
export const selection = createSelection();
